export default QuestionList = [
    { //1
        QuestionImage:  require ("../drawable/test1/question1/test1.png"),

        Answear1: require ("../drawable/test1/question1/answer11.png"),
        A1: 0,
        Answear2: require ("../drawable/test1/question1/answer12.png"),
        A2: 0,
        Answear3: require ("../drawable/test1/question1/answer13.png"),
        A3: 1,
        Answear4: require ("../drawable/test1/question1/answer14.png"),
        A4: 0,
        Answear5: require ("../drawable/test1/question1/answer15.png"),
        A5: 0,
        Answear6: require ("../drawable/test1/question1/answer16.png"),
        A6: 0,
    },
    { //2
        QuestionImage:  require ("../drawable/test1/question2/test2.png"),

        Answear1: require ("../drawable/test1/question2/answer21.png"),
        A1: 1,
        Answear2: require ("../drawable/test1/question2/answer22.png"),
        A2: 0,
        Answear3: require ("../drawable/test1/question2/answer23.png"),
        A3: 0,
        Answear4: require ("../drawable/test1/question2/answer24.png"),
        A4: 0,
        Answear5: require ("../drawable/test1/question2/answer25.png"),
        A5: 0,
        Answear6: require ("../drawable/test1/question2/answer26.png"),
        A6: 0,
    },
    { //3
        QuestionImage:  require ("../drawable/test1/question3/test3.png"),

        Answear1: require ("../drawable/test1/question3/answer31.png"),
        A1: 0,
        Answear2: require ("../drawable/test1/question3/answer32.png"),
        A2: 0,
        Answear3: require ("../drawable/test1/question3/answer33.png"),
        A3: 0,
        Answear4: require ("../drawable/test1/question3/answer34.png"),
        A4: 1,
        Answear5: require ("../drawable/test1/question3/answer35.png"),
        A5: 0,
        Answear6: require ("../drawable/test1/question3/answer36.png"),
        A6: 0,
    },
    { //4
        QuestionImage:  require ("../drawable/test1/question4/test4.png"),

        Answear1: require ("../drawable/test1/question4/answer41.png"),
        A1: 1,
        Answear2: require ("../drawable/test1/question4/answer42.png"),
        A2: 0,
        Answear3: require ("../drawable/test1/question4/answer43.png"),
        A3: 0,
        Answear4: require ("../drawable/test1/question4/answer44.png"),
        A4: 0,
        Answear5: require ("../drawable/test1/question4/answer45.png"),
        A5: 0,
        Answear6: require ("../drawable/test1/question4/answer46.png"),
        A6: 0,
    },
    {  //5
        QuestionImage:  require ("../drawable/test1/question5/test5.png"),

        Answear1: require ("../drawable/test1/question5/answer51.png"),
        A1: 0,
        Answear2: require ("../drawable/test1/question5/answer52.png"),
        A2: 0,
        Answear3: require ("../drawable/test1/question5/answer53.png"),
        A3: 0,
        Answear4: require ("../drawable/test1/question5/answer54.png"),
        A4: 0,
        Answear5: require ("../drawable/test1/question5/answer55.png"),
        A5: 1,
        Answear6: require ("../drawable/test1/question5/answer56.png"),
        A6: 0,
    },
    {  //6
        QuestionImage:  require ("../drawable/test1/question6/test6.png"),

        Answear1: require ("../drawable/test1/question6/answer61.png"),
        A1: 0,
        Answear2: require ("../drawable/test1/question6/answer62.png"),
        A2: 0,
        Answear3: require ("../drawable/test1/question6/answer63.png"),
        A3: 1,
        Answear4: require ("../drawable/test1/question6/answer64.png"),
        A4: 0,
        Answear5: require ("../drawable/test1/question6/answer65.png"),
        A5: 0,
        Answear6: require ("../drawable/test1/question6/answer66.png"),
        A6: 0,
    },
    {  //7
        QuestionImage:  require ("../drawable/test1/question7/test7.png"),

        Answear1: require ("../drawable/test1/question7/answer71.png"),
        A1: 0,
        Answear2: require ("../drawable/test1/question7/answer72.png"),
        A2: 1,
        Answear3: require ("../drawable/test1/question7/answer73.png"),
        A3: 0,
        Answear4: require ("../drawable/test1/question7/answer74.png"),
        A4: 0,
        Answear5: require ("../drawable/test1/question7/answer75.png"),
        A5: 0,
        Answear6: require ("../drawable/test1/question7/answer76.png"),
        A6: 0,
    },
    {  //8
        QuestionImage:  require ("../drawable/test1/question8/test8.png"),

        Answear1: require ("../drawable/test1/question8/answer81.png"),
        A1: 0,
        Answear2: require ("../drawable/test1/question8/answer82.png"),
        A2: 0,
        Answear3: require ("../drawable/test1/question8/answer83.png"),
        A3: 0,
        Answear4: require ("../drawable/test1/question8/answer84.png"),
        A4: 0,
        Answear5: require ("../drawable/test1/question8/answer85.png"),
        A5: 0,
        Answear6: require ("../drawable/test1/question8/answer86.png"),
        A6: 1,
    },
    {  //9
        QuestionImage:  require ("../drawable/test1/question9/test9.png"),

        Answear1: require ("../drawable/test1/question9/answer91.png"),
        A1: 0,
        Answear2: require ("../drawable/test1/question9/answer92.png"),
        A2: 0,
        Answear3: require ("../drawable/test1/question9/answer93.png"),
        A3: 0,
        Answear4: require ("../drawable/test1/question9/answer94.png"),
        A4: 0,
        Answear5: require ("../drawable/test1/question9/answer95.png"),
        A5: 1,
        Answear6: require ("../drawable/test1/question9/answer96.png"),
        A6: 0,
    },
    {  //10
        QuestionImage:  require ("../drawable/test1/question10/test10.png"),

        Answear1: require ("../drawable/test1/question10/answer101.png"),
        A1: 0,
        Answear2: require ("../drawable/test1/question10/answer102.png"),
        A2: 0,
        Answear3: require ("../drawable/test1/question10/answer103.png"),
        A3: 1,
        Answear4: require ("../drawable/test1/question10/answer104.png"),
        A4: 0,
        Answear5: require ("../drawable/test1/question10/answer105.png"),
        A5: 0,
        Answear6: require ("../drawable/test1/question10/answer106.png"),
        A6: 0,
    },
    {  //11
        QuestionImage:  require ("../drawable/test1/question11/test11.png"),

        Answear1: require ("../drawable/test1/question11/answer111.png"),
        A1: 0,
        Answear2: require ("../drawable/test1/question11/answer112.png"),
        A2: 0,
        Answear3: require ("../drawable/test1/question11/answer113.png"),
        A3: 0,
        Answear4: require ("../drawable/test1/question11/answer114.png"),
        A4: 0,
        Answear5: require ("../drawable/test1/question11/answer115.png"),
        A5: 1,
        Answear6: require ("../drawable/test1/question11/answer116.png"),
        A6: 0,
    },
    {  //12
        QuestionImage:  require ("../drawable/test1/question12/test12.png"),

        Answear1: require ("../drawable/test1/question12/answer121.png"),
        A1: 0,
        Answear2: require ("../drawable/test1/question12/answer122.png"),
        A2: 1,
        Answear3: require ("../drawable/test1/question12/answer123.png"),
        A3: 0,
        Answear4: require ("../drawable/test1/question12/answer124.png"),
        A4: 0,
        Answear5: require ("../drawable/test1/question12/answer125.png"),
        A5: 0,
        Answear6: require ("../drawable/test1/question12/answer126.png"),
        A6: 0,
    },
    {  //13
        QuestionImage:  require ("../drawable/test1/question13/test13.png"),

        Answear1: require ("../drawable/test1/question13/answer131.png"),
        A1: 0,
        Answear2: require ("../drawable/test1/question13/answer132.png"),
        A2: 0,
        Answear3: require ("../drawable/test1/question13/answer133.png"),
        A3: 1,
        Answear4: require ("../drawable/test1/question13/answer134.png"),
        A4: 0,
        Answear5: require ("../drawable/test1/question13/answer135.png"),
        A5: 0,
        Answear6: require ("../drawable/test1/question13/answer136.png"),
        A6: 0,
    },
    {  //14
        QuestionImage:  require ("../drawable/test1/question14/test14.png"),

        Answear1: require ("../drawable/test1/question14/answer141.png"),
        A1: 1,
        Answear2: require ("../drawable/test1/question14/answer142.png"),
        A2: 0,
        Answear3: require ("../drawable/test1/question14/answer143.png"),
        A3: 0,
        Answear4: require ("../drawable/test1/question14/answer144.png"),
        A4: 0,
        Answear5: require ("../drawable/test1/question14/answer145.png"),
        A5: 0,
        Answear6: require ("../drawable/test1/question14/answer146.png"),
        A6: 0,
    },
    {  //15
        QuestionImage:  require ("../drawable/test1/question15/test15.png"),

        Answear1: require ("../drawable/test1/question15/answer151.png"),
        A1: 0,
        Answear2: require ("../drawable/test1/question15/answer152.png"),
        A2: 0,
        Answear3: require ("../drawable/test1/question15/answer153.png"),
        A3: 1,
        Answear4: require ("../drawable/test1/question15/answer154.png"),
        A4: 0,
        Answear5: require ("../drawable/test1/question15/answer155.png"),
        A5: 0,
        Answear6: require ("../drawable/test1/question15/answer156.png"),
        A6: 0,
    },
    {  //16
        QuestionImage:  require ("../drawable/test1/question16/test16.png"),

        Answear1: require ("../drawable/test1/question16/answer161.png"),
        A1: 0,
        Answear2: require ("../drawable/test1/question16/answer162.png"),
        A2: 0,
        Answear3: require ("../drawable/test1/question16/answer163.png"),
        A3: 1,
        Answear4: require ("../drawable/test1/question16/answer164.png"),
        A4: 0,
        Answear5: require ("../drawable/test1/question16/answer165.png"),
        A5: 0,
        Answear6: require ("../drawable/test1/question16/answer166.png"),
        A6: 0,
    },
    {  //17
        QuestionImage:  require ("../drawable/test1/question17/test17.png"),

        Answear1: require ("../drawable/test1/question17/answer171.png"),
        A1: 0,
        Answear2: require ("../drawable/test1/question17/answer172.png"),
        A2: 1,
        Answear3: require ("../drawable/test1/question17/answer173.png"),
        A3: 0,
        Answear4: require ("../drawable/test1/question17/answer174.png"),
        A4: 0,
        Answear5: require ("../drawable/test1/question17/answer175.png"),
        A5: 0,
        Answear6: require ("../drawable/test1/question17/answer176.png"),
        A6: 0,
    },
    {  //18
        QuestionImage:  require ("../drawable/test1/question18/test18.png"),

        Answear1: require ("../drawable/test1/question18/answer181.png"),
        A1: 0,
        Answear2: require ("../drawable/test1/question18/answer182.png"),
        A2: 0,
        Answear3: require ("../drawable/test1/question18/answer183.png"),
        A3: 1,
        Answear4: require ("../drawable/test1/question18/answer184.png"),
        A4: 0,
        Answear5: require ("../drawable/test1/question18/answer185.png"),
        A5: 0,
        Answear6: require ("../drawable/test1/question18/answer186.png"),
        A6: 0,
    },
    {  //19
        QuestionImage:  require ("../drawable/test1/question19/test19.png"),

        Answear1: require ("../drawable/test1/question19/answer191.png"),
        A1: 0,
        Answear2: require ("../drawable/test1/question19/answer192.png"),
        A2: 1,
        Answear3: require ("../drawable/test1/question19/answer193.png"),
        A3: 0,
        Answear4: require ("../drawable/test1/question19/answer194.png"),
        A4: 0,
        Answear5: require ("../drawable/test1/question19/answer195.png"),
        A5: 0,
        Answear6: require ("../drawable/test1/question19/answer196.png"),
        A6: 0,
    },
    {  //20
        QuestionImage:  require ("../drawable/test1/question20/test20.png"),

        Answear1: require ("../drawable/test1/question20/answer201.png"),
        A1: 0,
        Answear2: require ("../drawable/test1/question20/answer202.png"),
        A2: 0,
        Answear3: require ("../drawable/test1/question20/answer203.png"),
        A3: 0,
        Answear4: require ("../drawable/test1/question20/answer204.png"),
        A4: 1,
        Answear5: require ("../drawable/test1/question20/answer205.png"),
        A5: 0,
        Answear6: require ("../drawable/test1/question20/answer206.png"),
        A6: 0,
    },
    {  //21
        QuestionImage:  require ("../drawable/test1/question21/test21.png"),

        Answear1: require ("../drawable/test1/question21/answer211.png"),
        A1: 0,
        Answear2: require ("../drawable/test1/question21/answer212.png"),
        A2: 0,
        Answear3: require ("../drawable/test1/question21/answer213.png"),
        A3: 0,
        Answear4: require ("../drawable/test1/question21/answer214.png"),
        A4: 0,
        Answear5: require ("../drawable/test1/question21/answer215.png"),
        A5: 0,
        Answear6: require ("../drawable/test1/question21/answer216.png"),
        A6: 1,
    },
    {  //22
        QuestionImage:  require ("../drawable/test1/question22/test22.png"),

        Answear1: require ("../drawable/test1/question22/answer221.png"),
        A1: 0,
        Answear2: require ("../drawable/test1/question22/answer222.png"),
        A2: 1,
        Answear3: require ("../drawable/test1/question22/answer223.png"),
        A3: 0,
        Answear4: require ("../drawable/test1/question22/answer224.png"),
        A4: 0,
        Answear5: require ("../drawable/test1/question22/answer225.png"),
        A5: 0,
        Answear6: require ("../drawable/test1/question22/answer226.png"),
        A6: 0,
    },
    {  //23
        QuestionImage:  require ("../drawable/test1/question23/test23.png"),

        Answear1: require ("../drawable/test1/question23/answer231.png"),
        A1: 0,
        Answear2: require ("../drawable/test1/question23/answer232.png"),
        A2: 0,
        Answear3: require ("../drawable/test1/question23/answer233.png"),
        A3: 0,
        Answear4: require ("../drawable/test1/question23/answer234.png"),
        A4: 0,
        Answear5: require ("../drawable/test1/question23/answer235.png"),
        A5: 0,
        Answear6: require ("../drawable/test1/question23/answer236.png"),
        A6: 1,
    },
    {  //24
        QuestionImage:  require ("../drawable/test1/question24/test24.png"),

        Answear1: require ("../drawable/test1/question24/answer241.png"),
        A1: 0,
        Answear2: require ("../drawable/test1/question24/answer242.png"),
        A2: 0,
        Answear3: require ("../drawable/test1/question24/answer243.png"),
        A3: 0,
        Answear4: require ("../drawable/test1/question24/answer244.png"),
        A4: 1,
        Answear5: require ("../drawable/test1/question24/answer245.png"),
        A5: 0,
        Answear6: require ("../drawable/test1/question24/answer246.png"),
        A6: 0,
    },
    {  //25
        QuestionImage:  require ("../drawable/test1/question25/test25.png"),

        Answear1: require ("../drawable/test1/question25/answer251.png"),
        A1: 0,
        Answear2: require ("../drawable/test1/question25/answer252.png"),
        A2: 0,
        Answear3: require ("../drawable/test1/question25/answer253.png"),
        A3: 1,
        Answear4: require ("../drawable/test1/question25/answer254.png"),
        A4: 0,
        Answear5: require ("../drawable/test1/question25/answer255.png"),
        A5: 0,
        Answear6: require ("../drawable/test1/question25/answer256.png"),
        A6: 0,
    },
]