export default QuestionList = [
    { //1
        QuestionImage:  require ("../drawable/test2/question1/test1.png"),

        Answear1: require ("../drawable/test2/question1/answer11.png"),
        A1: 0,
        Answear2: require ("../drawable/test2/question1/answer12.png"),
        A2: 0,
        Answear3: require ("../drawable/test2/question1/answer13.png"),
        A3: 1,
        Answear4: require ("../drawable/test2/question1/answer14.png"),
        A4: 0,
        Answear5: require ("../drawable/test2/question1/answer15.png"),
        A5: 0,
        Answear6: require ("../drawable/test2/question1/answer16.png"),
        A6: 0,
    },
    { //2
        QuestionImage:  require ("../drawable/test2/question2/test2.png"),

        Answear1: require ("../drawable/test2/question2/answer21.png"),
        A1: 0,
        Answear2: require ("../drawable/test2/question2/answer22.png"),
        A2: 0,
        Answear3: require ("../drawable/test2/question2/answer23.png"),
        A3: 1,
        Answear4: require ("../drawable/test2/question2/answer24.png"),
        A4: 0,
        Answear5: require ("../drawable/test2/question2/answer25.png"),
        A5: 0,
        Answear6: require ("../drawable/test2/question2/answer26.png"),
        A6: 0,
    },
    { //3
        QuestionImage:  require ("../drawable/test2/question3/test3.png"),

        Answear1: require ("../drawable/test2/question3/answer31.png"),
        A1: 1,
        Answear2: require ("../drawable/test2/question3/answer32.png"),
        A2: 0,
        Answear3: require ("../drawable/test2/question3/answer33.png"),
        A3: 0,
        Answear4: require ("../drawable/test2/question3/answer34.png"),
        A4: 0,
        Answear5: require ("../drawable/test2/question3/answer35.png"),
        A5: 0,
        Answear6: require ("../drawable/test2/question3/answer36.png"),
        A6: 0,
    },
    { //4
        QuestionImage:  require ("../drawable/test2/question4/test4.png"),

        Answear1: require ("../drawable/test2/question4/answer41.png"),
        A1: 0,
        Answear2: require ("../drawable/test2/question4/answer42.png"),
        A2: 0,
        Answear3: require ("../drawable/test2/question4/answer43.png"),
        A3: 0,
        Answear4: require ("../drawable/test2/question4/answer44.png"),
        A4: 1,
        Answear5: require ("../drawable/test2/question4/answer45.png"),
        A5: 0,
        Answear6: require ("../drawable/test2/question4/answer46.png"),
        A6: 0,
    },
    {  //5
        QuestionImage:  require ("../drawable/test2/question5/test5.png"),

        Answear1: require ("../drawable/test2/question5/answer51.png"),
        A1: 1,
        Answear2: require ("../drawable/test2/question5/answer52.png"),
        A2: 0,
        Answear3: require ("../drawable/test2/question5/answer53.png"),
        A3: 0,
        Answear4: require ("../drawable/test2/question5/answer54.png"),
        A4: 0,
        Answear5: require ("../drawable/test2/question5/answer55.png"),
        A5: 0,
        Answear6: require ("../drawable/test2/question5/answer56.png"),
        A6: 0,
    },
    {  //6
        QuestionImage:  require ("../drawable/test2/question6/test6.png"),

        Answear1: require ("../drawable/test2/question6/answer61.png"),
        A1: 0,
        Answear2: require ("../drawable/test2/question6/answer62.png"),
        A2: 1,
        Answear3: require ("../drawable/test2/question6/answer63.png"),
        A3: 0,
        Answear4: require ("../drawable/test2/question6/answer64.png"),
        A4: 0,
        Answear5: require ("../drawable/test2/question6/answer65.png"),
        A5: 0,
        Answear6: require ("../drawable/test2/question6/answer66.png"),
        A6: 0,
    },
    {  //7
        QuestionImage:  require ("../drawable/test2/question7/test7.png"),

        Answear1: require ("../drawable/test2/question7/answer71.png"),
        A1: 0,
        Answear2: require ("../drawable/test2/question7/answer72.png"),
        A2: 1,
        Answear3: require ("../drawable/test2/question7/answer73.png"),
        A3: 0,
        Answear4: require ("../drawable/test2/question7/answer74.png"),
        A4: 0,
        Answear5: require ("../drawable/test2/question7/answer75.png"),
        A5: 1,
        Answear6: require ("../drawable/test2/question7/answer76.png"),
        A6: 0,
    },
    {  //8
        QuestionImage:  require ("../drawable/test2/question8/test8.png"),

        Answear1: require ("../drawable/test2/question8/answer81.png"),
        A1: 0,
        Answear2: require ("../drawable/test2/question8/answer82.png"),
        A2: 0,
        Answear3: require ("../drawable/test2/question8/answer83.png"),
        A3: 0,
        Answear4: require ("../drawable/test2/question8/answer84.png"),
        A4: 0,
        Answear5: require ("../drawable/test2/question8/answer85.png"),
        A5: 0,
        Answear6: require ("../drawable/test2/question8/answer86.png"),
        A6: 1,
    },
    {  //9
        QuestionImage:  require ("../drawable/test2/question9/test9.png"),

        Answear1: require ("../drawable/test2/question9/answer91.png"),
        A1: 0,
        Answear2: require ("../drawable/test2/question9/answer92.png"),
        A2: 0,
        Answear3: require ("../drawable/test2/question9/answer93.png"),
        A3: 1,
        Answear4: require ("../drawable/test2/question9/answer94.png"),
        A4: 0,
        Answear5: require ("../drawable/test2/question9/answer95.png"),
        A5: 0,
        Answear6: require ("../drawable/test2/question9/answer96.png"),
        A6: 0,
    },
    {  //10
        QuestionImage:  require ("../drawable/test2/question10/test10.png"),

        Answear1: require ("../drawable/test2/question10/answer101.png"),
        A1: 0,
        Answear2: require ("../drawable/test2/question10/answer102.png"),
        A2: 0,
        Answear3: require ("../drawable/test2/question10/answer103.png"),
        A3: 0,
        Answear4: require ("../drawable/test2/question10/answer104.png"),
        A4: 1,
        Answear5: require ("../drawable/test2/question10/answer105.png"),
        A5: 0,
        Answear6: require ("../drawable/test2/question10/answer106.png"),
        A6: 0,
    },
    {  //11
        QuestionImage:  require ("../drawable/test2/question11/test11.png"),

        Answear1: require ("../drawable/test2/question11/answer111.png"),
        A1: 1,
        Answear2: require ("../drawable/test2/question11/answer112.png"),
        A2: 0,
        Answear3: require ("../drawable/test2/question11/answer113.png"),
        A3: 0,
        Answear4: require ("../drawable/test2/question11/answer114.png"),
        A4: 0,
        Answear5: require ("../drawable/test2/question11/answer115.png"),
        A5: 0,
        Answear6: require ("../drawable/test2/question11/answer116.png"),
        A6: 0,
    },
    {  //12
        QuestionImage:  require ("../drawable/test2/question12/test12.png"),

        Answear1: require ("../drawable/test2/question12/answer121.png"),
        A1: 0,
        Answear2: require ("../drawable/test2/question12/answer122.png"),
        A2: 1,
        Answear3: require ("../drawable/test2/question12/answer123.png"),
        A3: 0,
        Answear4: require ("../drawable/test2/question12/answer124.png"),
        A4: 0,
        Answear5: require ("../drawable/test2/question12/answer125.png"),
        A5: 0,
        Answear6: require ("../drawable/test2/question12/answer126.png"),
        A6: 0,
    },
    {  //13
        QuestionImage:  require ("../drawable/test2/question13/test13.png"),

        Answear1: require ("../drawable/test2/question13/answer131.png"),
        A1: 0,
        Answear2: require ("../drawable/test2/question13/answer132.png"),
        A2: 0,
        Answear3: require ("../drawable/test2/question13/answer133.png"),
        A3: 0,
        Answear4: require ("../drawable/test2/question13/answer134.png"),
        A4: 1,
        Answear5: require ("../drawable/test2/question13/answer135.png"),
        A5: 0,
        Answear6: require ("../drawable/test2/question13/answer136.png"),
        A6: 0,
    },
    {  //14
        QuestionImage:  require ("../drawable/test2/question14/test14.png"),

        Answear1: require ("../drawable/test2/question14/answer141.png"),
        A1: 0,
        Answear2: require ("../drawable/test2/question14/answer142.png"),
        A2: 0,
        Answear3: require ("../drawable/test2/question14/answer143.png"),
        A3: 0,
        Answear4: require ("../drawable/test2/question14/answer144.png"),
        A4: 1,
        Answear5: require ("../drawable/test2/question14/answer145.png"),
        A5: 0,
        Answear6: require ("../drawable/test2/question14/answer146.png"),
        A6: 0,
    },
]